### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/forms#24]
After the 1.2.6 release was made, @jdebeule fixed a few problems in `PackageInfo.g`; e/g/ the `PackageWWWHome` was wrong, and subsequently the `PackageInfoURL`. But that broke auto-updating. It would be good to get another release out with these fixes, so that the GAP package distribution will once again pick up future new releases of this packages. As it is, it won't ever go beyond 1.2.6 without manual intervention.

I could take care of this with <5 minutes of work, but then again @jdebeule may have his own plans...

**Comment by jdebeule** [comment]
I will try to fix it right now. This is indeed only admin. I might need help with the final release process, then I'll come back to you ;-)

**Comment by jdebeule** [comment]
Somehow I managed using ReleaseTools to create release 1.2.7. This is the final output:

`MacBook-Air-van-Jan-2:forms jdebeule$ GAP=/opt/gap-4.11.1/bin/gap.sh ../../ReleaseTools/release-gap-package --force
Extracting information from PackageInfo.g...
Package Forms 1.2.7
Building GAP package documentation (using makedoc.g)
Using archive basename forms-1.2.7
Using GitHub repository gap-packages/forms
Using GitHub username gap-packages
Using branch master
Using git tag v1.2.7 (derived from ArchiveURL in in PackageInfo.g)
Deleting existing release v1.2.7 from GitHub

Exporting repository content for tag 'v1.2.7'
Building GAP package documentation for archives (using makedoc.g)
Removing unnecessary files

Validating PackageInfo.g...

Creating forms-1.2.7.tar.gz ...
Creating forms-1.2.7.zip ...
Creating forms-1.2.7.tar.bz2 ...
Pushing your branch to GitHub
Everything up-to-date
Pushing your tag to GitHub
Everything up-to-date
Creating new release v1.2.7 on GitHub

Uploading forms-1.2.7.tar.gz with mime type application/x-gzip
######################################################################## 100,0%
Uploading forms-1.2.7.zip with mime type application/zip
######################################################################## 100,0%
Uploading forms-1.2.7.tar.bz2 with mime type application/x-bzip2
######################################################################## 100,0%

Uploading PDF
######################################################################## 100,0%
Updating website
Already up to date.
[gh-pages 5fecee4] Update website for Forms 1.2.7
 9 files changed, 51 insertions(+), 46 deletions(-)
 create mode 100644 _includes/button-bibtex.html.bak.bak
Pushing website changes
Enumerating objects: 26, done.
Counting objects: 100% (26/26), done.
Delta compression using up to 4 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (14/14), 1.57 KiB | 804.00 KiB/s, done.
Total 14 (delta 10), reused 1 (delta 0)
remote: Resolving deltas: 100% (10/10), completed with 10 local objects.
To https://github.com/gap-packages/forms
   3f34674..5fecee4  gh-pages -> gh-pages
Done
Your PackageInfo.g is now at https://gap-packages.github.io/forms/PackageInfo.g
MacBook-Air-van-Jan-2:forms jdebeule$ `

It mentions the update of the website, which, unfortunately, is not visible... However, the "tags" seem to be correct:

https://github.com/gap-packages/forms/releases/tag/v1.2.7

So main question: did I succeed?

**Comment by fingolfin** [comment]
It can take a couple minutes for the website to update, and indeed it is now visible on https://gap-packages.github.io/forms/ so yeah, it worked!

While I have your attention, maybe you also can take care of #16 and update the link(s) on http://cage.ugent.be/geometry/forms.php which point to bitbucket
