### ISSUE TITLE
Misleading function names: `IsOrthogonalMatrix`, `IsSymplecticMatrix`

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/forms#28]
The function `IsOrthogonalMatrix` checks if a matrix is symmetric, not whether it is orthogonal.

The function `IsSymplecticMatrix` likewise does not check if the matrix is contained in a symplectic group, but rather whether it is the Gram matrix of a symmetric form.

I think these functions should be renamed: the former might become `IsSymmetricMatrix`, the latter perhaps `FORMS_ IsSymplecticMatrix`

**Comment by jdebeule** [comment]
Yes, I fully agree! Changes made: IsOrthogonalMatrix -> FORMS_IsSymmetricMatrix, IsSymplecticMatrix -> FORMS_IsSymplecticMatrix, IsHermitianMatrix -> FORMS_IsHermitianMatrix.
